name: CI
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t ${( secrets.IMAGE_TAG )}:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        run: docker push ${( secrets.IMAGE_TAG )}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
